(self.AMP=self.AMP||[]).push({n:"amp-form",v:"1507685388117",f:(function(AMP){var l;function m(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function n(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var aa=Object.prototype.toString;function ba(a){if(!a)return[];for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return b};Date.now();self.log=self.log||{user:null,dev:null,userForEmbed:null};var q=self.log;function r(){if(!q.user)throw Error("failed to call initLogConstructor");return q.user};var ca=Object.prototype.hasOwnProperty;function da(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}
function ea(a,b){var c;c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.t=b.t;a.s=b.s;a.d=b.d;if(d.includes(a.s))throw Error("Source object has a circular reference.");d.push(a.s);a.t!==a.s&&(a.d>c?Object.assign(a.t,a.s):(Object.keys(a.s).forEach(function(a){return function(b){var c=a.s[b];if(ca.call(a.t,b)){var d=a.t[b];if("[object Object]"===aa.call(c)&&"[object Object]"===aa.call(d)){e.push({t:d,s:c,d:a.d+1});return}}a.t[b]=c}}(a)),a={s:a.s,t:a.t,d:a.d}))}}
;function fa(a,b){if(a.nodeType){var c=(a.ownerDocument||a).defaultView;if(c=c!=(c.__AMP_TOP||c)&&ga(c,b)?t(c,b):null)return c}return u(a,b)}function v(a,b){a=a.__AMP_TOP||a;return t(a,b)}function u(a,b){a=w(a);a=y(a);return t(a,b)}function w(a){return a.nodeType?v((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function y(a){a=w(a);return a.isSingleDoc()?a.win:a}
function t(a,b){ga(a,b);var c=z(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function ha(a){var b=ia(a);if(b)return b;var c,d=new Promise(function(a){c=a});z(a)["amp-analytics-instrumentation"]={obj:null,promise:d,resolve:c,context:null,ctor:null};return d}
function ia(a){var b=z(a)["amp-analytics-instrumentation"];if(b){if(b.promise)return b.promise;t(a,"amp-analytics-instrumentation");return b.promise=Promise.resolve(b.obj)}return null}function z(a){var b=a.services;b||(b=a.services={});return b}function ga(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var A;function ja(a,b){for(var c=[],d=a.parentElement;d;d=d.parentElement)b(d)&&c.push(d);return c}function ka(a){var b="fieldset",b=b.toUpperCase();return ja(a,function(a){return a.tagName==b})}function B(a,b){for(var c=0,d;void 0!==(d=a[c]);c++)b(d,c)};function la(a){return a.ampExtendedElements?!!a.ampExtendedElements["amp-analytics"]:!1}function ma(a){var b=w(a),c=ia(y(a));return c?c:Promise.resolve().then(function(){return la(b.win)?ha(y(a)):b.whenBodyAvailable().then(function(){return la(b.win)?ha(y(a)):null})})};var C=self.AMP_CONFIG||{},na=("string"==typeof C.cdnProxyRegex?new RegExp(C.cdnProxyRegex):C.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;var D,E;
function F(a){var b;D||(D=self.document.createElement("a"),E=self.UrlCache||(self.UrlCache=Object.create(null)));var c=E[a];if(c)return c;var d=D;d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=d.origin&&
"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;var h=e,f=h;return b?f:E[a]=f}function oa(a){"string"==typeof a&&(a=F(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function pa(a,b,c){c=void 0===c?"source":c;r().assert(null!=a,"%s %s must be available",b,c);var d=a;r().assert(oa(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)}function qa(a){"string"==typeof a&&(a=F(a));return na.test(a.origin)};var G,ra="Webkit webkit Moz moz ms O o".split(" ");function sa(a,b){for(var c in b){var d=a,e=b[c],h;h=d.style;var f=c;if(n(f,"--"))h=f;else{G||(G=da());var g=G[f];if(!g){g=f;if(void 0===h[f]){var k;k=f;k=k.charAt(0).toUpperCase()+k.slice(1);b:{for(var p=0;p<ra.length;p++){var x=ra[p]+k;if(void 0!==h[x]){k=x;break b}}k=""}void 0!==h[k]&&(g=k)}G[f]=g}h=g}h&&(d.style[h]=e)}};function ta(a,b){var c="form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}.i-amphtml-validation-bubble{-webkit-transform:translate(-50%,-100%);transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,.5);max-width:200px;position:absolute;display:none;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:' ';position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{display:none;color:red}[visible-when-invalid].visible{display:initial}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/",
d=!1,e="amp-form",h=a.getHeadNode(),f=ua(h,va(h,c),d||!1,e||null);if(b){var g=a.getRootNode();if(wa(g,f))b(f);else var k=setInterval(function(){wa(g,f)&&(clearInterval(k),b(f))},4)}}
function ua(a,b,c,d){var e=a.__AMP_CSS_SM;e||(e=a.__AMP_CSS_SM=da());var h=!c&&d&&"amp-custom"!=d&&"amp-keyframes"!=d,f=c?"amp-runtime":h?"amp-extension="+d:null;if(f){var g=xa(a,e,f);if(g)return g}var k=(a.ownerDocument||a).createElement("style");k.textContent=b;var p=null;c?k.setAttribute("amp-runtime",""):h?(k.setAttribute("amp-extension",d||""),p=xa(a,e,"amp-runtime")):(d&&k.setAttribute(d,""),p=a.lastChild);(b=p)?b.nextSibling?a.insertBefore(k,b.nextSibling):a.appendChild(k):a.insertBefore(k,
a.firstChild);f&&(e[f]=k);return k}function xa(a,b,c){return b[c]?b[c]:(a=a.querySelector("style["+c+"]"))?b[c]=a:null}function va(a,b){return(a=a.__AMP_CSS_TR)?a(b):b}function wa(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++){var d=c[a];if(d.ownerNode==b)return!0}return!1};function H(a,b,c){ma(a).then(function(d){d&&d.triggerEventForTarget(a,b,c)})};function I(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a};function J(a){var b,c;this.L=new Promise(function(a,d){b=a;c=d});this.V=b;this.T=c;this.D=0;if(a)for(var d=0;d<a.length;d++)this.add(a[d])}J.prototype.add=function(a){var b=this,c=++this.D;Promise.resolve(a).then(function(a){b.D===c&&b.V(a)},function(a){b.D===c&&b.T(a)});return this.L};J.prototype.then=function(a,b){return this.L.then(a,b)};function ya(a){var b=a.ownerDocument.defaultView;b.FormProxy||(b.FormProxy=za(b));var c=b.FormProxy,d=new c(a);"action"in d||Aa(a,d);a.$p=d}
function za(a){function b(a){this.a=a}var c=b.prototype,d=[a.HTMLFormElement,a.HTMLElement,a.Element,a.Node,a.EventTarget];d.forEach(function(b){var d=b&&b.prototype;b={};for(var e in d)if(b.property=a.Object.getOwnPropertyDescriptor(d,e),b.property&&e.toUpperCase()!=e&&!n(e,"on")&&!a.Object.prototype.hasOwnProperty.call(c,e)){if("function"==typeof b.property.value)b.method=b.property.value,c[e]=function(a){return function(){return a.method.apply(this.a,arguments)}}(b);else{var g={};b.property.get&&
(g.get=function(a){return function(){return a.property.get.call(this.a)}}(b));b.property.set&&(g.set=function(a){return function(b){return a.property.set.call(this.a,b)}}(b));a.Object.defineProperty(c,e,g)}b={method:b.method,property:b.property}}});return b}
function Aa(a,b){var c=a.ownerDocument.defaultView.HTMLFormElement.prototype.cloneNode.call(a,!1),d={},e;for(e in c)if(d.name=e,!(d.name in b||d.name.toUpperCase()==d.name||n(d.name,"on"))){d.desc=Ba[d.name];var h=a[d.name];if(d.desc)if(d.desc.access==K){d.actual=void 0;if(h&&h.nodeType){var c=h,f=c.nextSibling,g=c.parentNode;g.removeChild(c);try{d.actual=a[d.name]}finally{g.insertBefore(c,f)}}else d.actual=h;Object.defineProperty(b,d.name,{get:function(a){return function(){return a.actual}}(d)})}else d.desc.access==
L&&(d.attr=d.desc.attr||d.name,Object.defineProperty(b,d.name,{get:function(a){return function(){var c=b.getAttribute(a.attr);null==c&&void 0!==a.desc.def?c=a.desc.def:a.desc.type==Ca?c="true"===c:a.desc.type==M?c=null!=c:a.desc.type==Da&&(c=F(c||"").href);return c}}(d),set:function(a){return function(c){a.desc.type==M&&(c=c?"":null);null!=c?b.setAttribute(a.attr,c):b.removeAttribute(a.attr)}}(d)}));else Object.defineProperty(b,d.name,{get:function(b){return function(){return a[b.name]}}(d),set:function(b){return function(c){a[b.name]=
c}}(d)});d={actual:d.actual,attr:d.attr,desc:d.desc,name:d.name}}}
var L=1,K=2,Da=1,Ca=2,M=3,Ba={acceptCharset:{access:L,attr:"accept-charset"},accessKey:{access:L,attr:"accesskey"},action:{access:L,type:Da},attributes:{access:K},autocomplete:{access:L,def:"on"},children:{access:K},dataset:{access:K},dir:{access:L},draggable:{access:L,type:Ca,def:!1},elements:{access:K},encoding:{access:K},enctype:{access:L},hidden:{access:L,type:M,def:!1},id:{access:L,def:""},lang:{access:L},localName:{access:K},method:{access:L,def:"get"},name:{access:L},noValidate:{access:L,attr:"novalidate",
type:M,def:!1},prefix:{access:K},spellcheck:{access:L},style:{access:K},target:{access:L,def:""},title:{access:L},translate:{access:L}};function N(a){var b={},c=a.elements,d=/^(?:input|select|textarea)$/i,e=/^(?:button|image|file|reset)$/i,h=/^(?:checkbox|radio)$/i;for(a=0;a<c.length;a++){var f=c[a],g;if(g=f.name){a:if(f.disabled)g=!0;else{g=ka(f);for(var k=0;k<g.length;k++)if(g[k].disabled){g=!0;break a}g=!1}g=!g}!g||!d.test(f.tagName)||e.test(f.type)||h.test(f.type)&&!f.checked||(void 0===b[f.name]&&(b[f.name]=[]),b[f.name].push(f.value))}return b};function O(a,b){this.I=b;this.aa=u(a,"viewport");this.A=v(a.win,"vsync");this.G=null;this.F="";this.u=!1;this.h=a.win.document.createElement("div");this.h.classList.add("i-amphtml-validation-bubble");this.h.__BUBBLE_OBJ=this;a.getBody().appendChild(this.h)}O.prototype.isActiveOn=function(a){return this.u&&a==this.G};O.prototype.hide=function(){this.u&&(this.u=!1,this.G=null,this.F="",this.A.run({measure:void 0,mutate:Ea},{bubbleElement:this.h}))};
O.prototype.show=function(a,b){if(!this.isActiveOn(a)||b!=this.F){this.u=!0;this.G=a;this.F=b;var c={message:b,targetElement:a,bubbleElement:this.h,viewport:this.aa,id:this.I};this.A.run({measure:Fa,mutate:Ga},c)}};function Ea(a){a.bubbleElement.removeAttribute("aria-alert");a.bubbleElement.removeAttribute("role");for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);sa(a.bubbleElement,{display:"none"})}function Fa(a){a.targetRect=a.viewport.getLayoutRect(a.targetElement)}
function Ga(a){for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);var c=a.bubbleElement.ownerDocument.createElement("div");c.id="bubble-message-"+a.id;c.textContent=a.message;a.bubbleElement.setAttribute("aria-labeledby",c.id);a.bubbleElement.setAttribute("role","alert");a.bubbleElement.setAttribute("aria-live","assertive");a.bubbleElement.appendChild(c);sa(a.bubbleElement,{display:"block",top:a.targetRect.top-10+"px",left:a.targetRect.left+a.targetRect.width/2+"px"})};var Ha,Ia,Ja=0;function P(a){this.form=a;this.ampdoc=w(a);this.doc=a.ownerDocument;this.m=null}P.prototype.report=function(){};P.prototype.onBlur=function(){};P.prototype.onInput=function(){};P.prototype.fireValidityEventIfNecessary=function(){var a=this.m;this.m=this.form.checkValidity();if(a!==this.m){var b=I(this.form.ownerDocument.defaultView,this.m?"valid":"invalid",null,{bubbles:!0});this.form.dispatchEvent(b)}};function Ka(a){P.apply(this,arguments)}m(Ka,P);
Ka.prototype.report=function(){this.form.reportValidity();this.fireValidityEventIfNecessary()};function Q(a){P.call(this,a);var b="i-amphtml-validation-bubble-"+Ja++;this.i=new O(this.ampdoc,b)}m(Q,P);Q.prototype.report=function(){for(var a=this.form.querySelectorAll("input,select,textarea"),b=0;b<a.length;b++)if(!a[b].checkValidity()){a[b].focus();this.i.show(a[b],a[b].validationMessage);break}this.fireValidityEventIfNecessary()};Q.prototype.onBlur=function(){this.i.hide()};
Q.prototype.onInput=function(a){a=a.target;this.i.isActiveOn(a)&&(a.checkValidity()?(a.removeAttribute("aria-invalid"),this.i.hide()):(a.setAttribute("aria-invalid","true"),this.i.show(a,a.validationMessage)))};function R(a){P.call(this,a);this.J={};this.o={}}m(R,P);l=R.prototype;l.reportInput=function(a){var b;a:{for(b in a.validity)if(a.validity[b])break a;b=null}var c=b;c&&this.showValidationFor(a,c)};l.hideAllValidations=function(){for(var a in this.o){var b=this.doc.getElementById(a);this.hideValidationFor(b)}};
l.getValidationFor=function(a,b){if(!a.id)return null;a="[visible-when-invalid="+b+"]"+("[validation-for="+a.id+"]");void 0===this.J[a]&&(this.J[a]=this.doc.querySelector(a));return this.J[a]};l.showValidationFor=function(a,b){var c=this.getValidationFor(a,b);c&&(c.textContent.trim()||(c.textContent=a.validationMessage),a.setAttribute("aria-invalid","true"),c.classList.add("visible"),this.o[a.id]=c)};
l.hideValidationFor=function(a){var b=this.getVisibleValidationFor(a);b&&(a.removeAttribute("aria-invalid"),b.classList.remove("visible"),delete this.o[a.id])};l.getVisibleValidationFor=function(a){return a.id?this.o[a.id]:null};l.shouldValidateOnInteraction=function(){throw Error("Not Implemented");};l.onInteraction=function(a){a=a.target;var b=this.shouldValidateOnInteraction(a);this.hideValidationFor(a);b&&!a.checkValidity()&&this.reportInput(a)};l.onBlur=function(a){this.onInteraction(a)};
l.onInput=function(a){this.onInteraction(a)};function S(a){R.apply(this,arguments)}m(S,R);S.prototype.report=function(){this.hideAllValidations();for(var a=this.form.querySelectorAll("input,select,textarea"),b=0;b<a.length;b++)if(!a[b].checkValidity()){this.reportInput(a[b]);a[b].focus();break}this.fireValidityEventIfNecessary()};S.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function T(a){R.apply(this,arguments)}m(T,R);
T.prototype.report=function(){this.hideAllValidations();for(var a=null,b=this.form.querySelectorAll("input,select,textarea"),c=0;c<b.length;c++)b[c].checkValidity()||(a=a||b[c],this.reportInput(b[c]));a&&a.focus();this.fireValidityEventIfNecessary()};T.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function U(a){R.apply(this,arguments)}m(U,R);U.prototype.shouldValidateOnInteraction=function(){return!0};
U.prototype.onInteraction=function(a){R.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};function V(a){T.apply(this,arguments)}m(V,T);V.prototype.shouldValidateOnInteraction=function(){return!0};V.prototype.onInteraction=function(a){T.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};
function La(a){var b=a.getAttribute("custom-validation-reporting");switch(b){case "as-you-go":return new U(a);case "show-all-on-submit":return new T(a);case "interact-and-submit":return new V(a);case "show-first-on-submit":return new S(a)}a.ownerDocument&&void 0===Ha&&(Ha=!!document.createElement("form").reportValidity);return Ha?new Ka(a):new Q(a)};function Ma(a,b){return a.hasAttribute("verify-xhr")?new Na(a,b):new Oa(a)}function W(a){this.a=a}W.prototype.onCommit=function(){Pa(this);return Qa(this)?this.P():Promise.resolve([])};W.prototype.P=function(){return Promise.resolve([])};
function Qa(a){a=a.a.elements;for(var b=0;b<a.length;b++){var c=a[b];if(!c.disabled)switch(c.type){case "select-multiple":case "select-one":for(var c=c.options,d=0;d<c.length;d++)if(c[d].selected!==c[d].defaultSelected)return!0;break;case "checkbox":case "radio":if(c.checked!==c.defaultChecked)return!0;break;default:if(c.value!==c.defaultValue)return!0}}return!1}function Pa(a){(a=a.a.elements)&&B(a,function(a){a.setCustomValidity("")})}function Oa(a){W.apply(this,arguments)}m(Oa,W);
function Na(a,b){this.a=a;this.l=b;this.j=null;this.K=[]}m(Na,W);Na.prototype.P=function(){var a=this,b=this.l().then(function(){return[]},function(a){return Ra(a)});return Sa(this,b).then(function(b){return Ta(a,b)})};function Sa(a,b){if(!a.j){a.j=new J;var c=function(){return a.j=null};a.j.then(c,c)}return a.j.add(b)}
function Ta(a,b){function c(a){return b.every(function(b){return a.name!==b.name})}var d=[],e=a.K;a.K=b;for(var h=0;h<b.length;h++){var f=b[h],g=r().assertString(f.name,"Verification errors must have a name property"),f=r().assertString(f.message,"Verification errors must have a message property"),g=r().assertElement(a.a.querySelector('[name="'+g+'"]'),"Verification error name property must match a field name");g.checkValidity()&&(g.setCustomValidity(f),d.push(g))}var k=e.filter(c).map(function(b){return a.a.querySelector('[name="'+
b.name+'"]')});return d.concat(k)}function Ra(a){return(a=a.response)?a.json().then(function(a){return a.verifyErrors||[]},function(){return[]}):Promise.resolve([])};var Ua=["amp-selector"];
function Va(a,b){var c=this;try{ya(a)}catch(h){var d;if(q.dev)d=q.dev;else throw Error("failed to call initLogConstructor");d.error("amp-form","form proxy failed to install",h)}a.__AMP_FORM=this;this.I=b;this.b=a.ownerDocument.defaultView;this.Z=v(this.b,"timer");this.O=fa(a,"url-replace");this.H=null;this.a=a;this.A=v(this.b,"vsync");this.N=v(this.b,"templates");this.ea=v(this.b,"xhr");this.C=fa(this.a,"action");this.W=u(this.a,"resources");this.g=(this.a.getAttribute("method")||"GET").toUpperCase();
this.Y=this.a.getAttribute("target");this.B=Wa(this,"action-xhr");this.da=Wa(this,"verify-xhr");this.fa=void 0;this.M=!this.a.hasAttribute("novalidate");this.a.setAttribute("novalidate","");this.M||this.a.setAttribute("amp-novalidate","");this.a.classList.add("i-amphtml-form");var e=this.a.querySelectorAll('[type="submit"]');this.X=ba(e);this.c="initial";a=this.a.elements;for(b=0;b<a.length;b++)d=a[b].name,r().assert("__amp_source_origin"!=d&&"__amp_form_verify"!=d,"Illegal input name, %s found: %s",
d,a[b]);this.w=La(this.a);this.$=Ma(this.a,function(){return Xa(c)});this.C.installActionHandler(this.a,this.R.bind(this),100);Ya(this);this.U=this.ca=null}function Wa(a,b){var c=a.a.getAttribute(b);c&&(pa(c,a.a,b),r().assert(!qa(c),"form "+b+" should not be on AMP CDN: %s",a.a));return c}l=Va.prototype;l.R=function(a){var b=this;"submit"==a.method&&Za(this).then(function(){var c=a;"submitting"!=b.c&&$a(b)&&(ab(b,c.trust),"GET"!=b.g||b.B||b.a.submit())});return null};
function Za(a){if(a.H)return a.H;var b=a.a.querySelectorAll(Ua.join(",")),c=ba(b).map(function(a){return a.whenBuilt()});return a.H=bb(a,c,2E3)}
function Ya(a){function b(){"verifying"===a.c&&X(a,"initial")}a.a.addEventListener("submit",a.S.bind(a),!0);a.a.addEventListener("blur",function(b){Y(b.target);a.w.onBlur(b)},!0);a.a.addEventListener("change",function(c){a.$.onCommit().then(function(b){b.forEach(Y);a.w.onBlur(c)},function(){Y(c.target)}).then(b,b)});a.a.addEventListener("input",function(b){Y(b.target);a.w.onInput(b)})}
function cb(a){var b={},c=N(a.a),d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(b["formFields["+d+"]"]=c[d].join(","));b.formId=a.a.id;H(a.a,"amp-form-submit",b)}l.S=function(a){"submitting"!=this.c&&$a(this)?((this.B||"POST"==this.g)&&a.preventDefault(),ab(this,100)):(a.stopImmediatePropagation(),a.preventDefault())};
function ab(a,b){var c=db(a);if(a.B)eb(a,c,b);else if("POST"==a.g)r().assert(!1,"Only XHR based (via action-xhr attribute) submissions are support for POST requests. %s",a.a);else if("GET"==a.g){for(var d=c,e=0;e<d.length;e++)a.O.expandInputValueSync(d[e]);cb(a)}}function db(a){return a.a.querySelectorAll('[type="hidden"][data-amp-replace]')}
function Xa(a){if("submitting"===a.c)return Promise.resolve();X(a,"verifying");return fb(a,db(a)).then(function(){var b={};return a.l(a.da,a.g,(b.__amp_form_verify=!0,b))})}function eb(a,b,c){X(a,"submitting");fb(a,b).then(function(){cb(a);a.C.trigger(a.a,"submit",null,c);var b=N(a.a);gb(a,b)}).then(function(){return a.l(a.B,a.g)}).then(function(b){return hb(a,b)},function(b){return ib(a,b)})}
function fb(a,b){for(var c=[],d=0;d<b.length;d++)c.push(a.O.expandInputValueAsync(b[d]));return bb(a,c,100)}
l.l=function(a,b,c){var d,e,h="GET"==b||"HEAD"==b;if(h){var f=N(this.a);c&&ea(f,c);var g=[],k;for(k in f){var p=f[k];if(null!=p)if(Array.isArray(p))for(var x=0;x<p.length;x++){var nb=p[x];g.push(encodeURIComponent(k)+"="+encodeURIComponent(nb))}else g.push(encodeURIComponent(k)+"="+encodeURIComponent(p))}(k=g.join("&"))?(a=a.split("#",2),f=a[0].split("?",2),k=f[0]+(f[1]?"?"+f[1]+"&"+k:"?"+k),d=k+=a[1]?"#"+a[1]:""):d=a}else for(f in d=a,e=new FormData(this.a),c)e.append(f,c[f]);return this.ea.fetch(d,
{body:e,method:b,credentials:"include",headers:{Accept:"application/json"}})};function hb(a,b){return b.json().then(function(c){jb(a,!0,c);H(a.a,"amp-form-submit-success",void 0);X(a,"submit-success");gb(a,c||{});kb(a,b)},function(a){r().error("amp-form","Failed to parse response JSON: "+a)})}
function ib(a,b){return(b&&b.response?b.response.json().catch(function(){return null}):Promise.resolve(null)).then(function(c){jb(a,!1,c);H(a.a,"amp-form-submit-error",void 0);X(a,"submit-error");gb(a,c||{});kb(a,b.response);r().error("amp-form","Form submission failed: "+b)})}function $a(a){void 0===Ia&&(Ia=!!a.b.document.createElement("input").checkValidity);if(Ia){var b=lb(a.a);if(a.M)return a.A.run({measure:void 0,mutate:mb},{validator:a.w}),b}return!0}
function kb(a,b){if(b&&b.headers){var c=b.headers.get("AMP-Redirect-To");if(c){r().assert("_blank"!=a.Y,"Redirecting to target=_blank using AMP-Redirect-To is currently not supported, use target=_top instead. %s",a.a);try{b=c,r().assert(/^https?\:/i.test(b),'URL must start with "http://" or "https://". Invalid value: %s',b),F(b),pa(c,"AMP-Redirect-To","Url")}catch(d){r().assert(!1,"The `AMP-Redirect-To` header value must be an absolute URL starting with https://. Found %s",c)}a.b.top.location.href=
c}}}function jb(a,b,c){var d=b?"submit-success":"submit-error";c=I(a.b,"amp-form."+d,{response:c});a.C.trigger(a.a,d,c,100)}function bb(a,b,c){return Promise.race([Promise.all(b),a.Z.promise(c)])}function X(a,b){var c=a.c;a.a.classList.remove("amp-form-"+c);a.a.classList.add("amp-form-"+b);ob(a,c);a.c=b;a.X.forEach(function(a){"submitting"==b?a.setAttribute("disabled",""):a.removeAttribute("disabled")})}
function gb(a,b){var c=a.a.querySelector("["+a.c+"]");if(c){var d="rendered-message-"+a.I;c.setAttribute("role","alert");c.setAttribute("aria-labeledby",d);c.setAttribute("aria-live","assertive");a.N.hasTemplate(c)?a.N.findAndRenderTemplate(c,b).then(function(b){b.id=d;b.setAttribute("i-amphtml-rendered","");c.appendChild(b);var e=I(a.b,"amp:dom-update",null,{bubbles:!0});c.dispatchEvent(e)}):(a.W.mutateElement(c,function(){}),Promise.resolve())}}
function ob(a,b){if(a=a.a.querySelector("["+b+"]")){if(null==A)try{a.ownerDocument.querySelector(":scope"),A=!0}catch(d){A=!1}A?a=a.querySelector(":scope > [i-amphtml-rendered]"):(a.classList.add("i-amphtml-scoped"),b=a.querySelector(".i-amphtml-scoped > [i-amphtml-rendered]"),a.classList.remove("i-amphtml-scoped"),a=b);var c=a;c&&(a=c,a.parentElement&&a.parentElement.removeChild(a))}}l.ha=function(){return this.ca};l.ga=function(){return this.U};function mb(a){a.validator.report()}
function lb(a){var b=a.querySelectorAll("input,select,textarea,fieldset");B(b,function(a){return Z(a)});return Z(a)}
function Z(a,b){b=void 0===b?!1:b;if(!a.checkValidity)return!0;var c=!1,d=a.classList.contains("user-valid")?"valid":a.classList.contains("user-invalid")?"invalid":"none",e=a.checkValidity();"valid"!=d&&e?(a.classList.add("user-valid"),a.classList.remove("user-invalid"),c="invalid"==d):"invalid"==d||e||(a.classList.add("user-invalid"),a.classList.remove("user-valid"),c=!0);if(a.validity)for(var h in a.validity)a.classList.toggle(h,a.validity[h]);if(b&&c){h=ka(a);for(var f=0;f<h.length;f++)Z(h[f]);
a.form&&Z(a.form)}return e}function Y(a){Z(a,!0)}function pb(a){this.ba=qb(a).then(function(){return rb(a)})}pb.prototype.whenInitialized=function(){return this.ba};function qb(a){return new Promise(function(b){ta(a,b)})}function rb(a){return a.whenReady().then(function(){sb(a.getRootNode().querySelectorAll("form"));tb(a.getRootNode())})}function sb(a){a&&B(a,function(a,c){var b=a.__AMP_FORM||null;b||new Va(a,"amp-form-"+c)})}
function tb(a){a.addEventListener("amp:dom-update",function(){sb(a.querySelectorAll("form"))})}(function(a){a.registerServiceForDoc("amp-form",pb)})(self.AMP);
})});
//# sourceMappingURL=amp-form-0.1.js.map

